// Auto-generated TypeScript definitions from niimathOperators.json
// Do not edit this file directly - it will be overwritten

export interface OperatorDefinition {
  args?: string[];
  help?: string;
  subOperations?: Record<string, { args: string[]; help: string }>;
}

export type Operators = Record<string, OperatorDefinition>;

// Mesh sub-operation options
export interface MeshOptions {
  /** 'd'ark, 'm'edium, 'b'right or numeric isosurface */
  i?: string | number;
  /** roi based atlas to mesh */
  a?: string | number;
  /** fill bubbles */
  b?: string | number;
  /** only largest */
  l?: string | number;
  /** original marching cubes */
  o?: string | number;
  /** quality */
  q?: string | number;
  /** post smooth */
  s?: string | number;
  /** reduce fraction */
  r?: string | number;
  /** verbose */
  v?: string | number;
}

// Bitmap sub-operation options
export interface BitmapOptions {
  /** axial, coronal, sagittal at midpoint (0.5) */
  a?: boolean;
  /** mosaic view with slices at 0.25, 0.5, 0.75 for each axis */
  m?: boolean;
  /** automatically select largest plane orientation */
  o?: boolean;
  /** sagittal slice(s) at specified position(s) */
  x?: string | number;
  /** coronal slice(s) at specified position(s) */
  y?: string | number;
  /** axial slice(s) at specified position(s) */
  z?: string | number;
  /** same as -x/-y/-z but draw crosshairs from other axes */
  X?: string | number;
  /** insert row separator between slice groups */
  r?: boolean;
  /** flip left-right (0=neurological/default=1 radiological) */
  f?: boolean;
  /** show L/R labels (default=1) */
  u?: boolean;
  /** interpolation (0=nearest neighbor, 1=linear) */
  n?: boolean;
  /** scale factor for output image size */
  s?: string | number;
  /** intensity range for base image */
  t?: (string | number)[];
  /** intensity range for overlay image */
  T?: (string | number)[];
  /** base image RGBA tint (values 0.0-1.0) */
  c?: (string | number)[];
  /** overlay RGBA color (values 0.0-1.0) */
  C?: (string | number)[];
  /** background RGBA color (values 0.0-1.0) */
  b?: (string | number)[];
  /** use negative colormap for overlay (blue-green for negative values) */
  N?: boolean;
  /** apply edge detection to overlay */
  e?: boolean;
}

// ImageProcessor method signatures
export interface ImageProcessorMethods {
  /** Butterworth filter, highpass and lowpass in Hz,TR in seconds (zero-phase 2*2nd order filtfilt) */
  bandpass(hp: string | number, lp: string | number, tr: string | number): this;
  /** create PNG bitmap from NIfTI volume */
  bitmap(outputPath: string, options?: BitmapOptions): this;
  /** Same as bptf but does not remove mean (emulates fslmaths < 5.0.7) */
  bptfm(hp: string | number, lp: string | number): this;
  /** Connected component labelling for non-zero voxels (conn sets neighbors: 6, 18, 26) */
  bwlabel(conn: string | number): this;
  /** reverse h2c transform */
  c2h(): this;
  /** round voxels upwards to the nearest integer */
  ceil(): this;
  /** reorder and flip dimensions to RAS orientation */
  ras(): this;
  /** reslice to 1mm size in coronal slice direction with 256^3 voxels */
  conform(): this;
  /** conform to axial slice with dx*dy*dzmm size and dx*dy*dz voxels. f_high bright clamping (0.98 for top 2%). Linear (1) or nearest-neighbor (0) */
  comply(nx: string | number, ny: string | number, nz: string | number, dx: string | number, dy: string | number, dz: string | number, f_high: string | number, isLinear: string | number): this;
  /** reslice to match image 'target' using linear interpolation */
  reslice(target: string | number): this;
  /** reslice to match image 'target' using nearest neighbor interpolation */
  reslice_nn(target: string | number): this;
  /** reslice mask to current image using nearest neighbor; set voxels ≤ 0 in mask to minimum intensity */
  reslice_mask(mask: string | number): this;
  /** morphological close that binarizes with `thr`, dilates with `dx1` and erodes with `dx2` (fills bubbles with `thr`) */
  close(thr: string | number, dx1: string | number, dx2: string | number): this;
  /** remove volumes, starts with 0 not 1! Inputting -1 for a size will set it to the full range */
  crop(tmin: string | number, tsize: string | number): this;
  /** set dark voxels to zero (mode 1..5; higher yields more surviving voxels) */
  dehaze(mode: string | number): this;
  /** remove linear trend (and mean) from input */
  detrend(): this;
  /** remove average signal across volumes (requires 4D input) */
  demean(): this;
  /** morphological bilate binarizes with `thr`, grows up to distance `dx` */
  dilate(thr: string | number, dx: string | number): this;
  /** estimate Euler Distance Transform (distance field). Assumes isotropic input */
  edt(): this;
  /** compute scalar field of local vector contrast (Euclidean distance between each voxel and its neighbors; useful for RGB or multi-channel data) */
  edginess(): this;
  /** morphological erode binarizes with `thr`, shrinks within distance `dx` */
  erode(thr: string | number, dx: string | number): this;
  /** round voxels downwards to the nearest integer */
  floor(): this;
  /** NIfTI gzip mode (0=uncompressed, 1=compressed, else FSL environment; default -1) */
  gz(mode: string | number): this;
  /** convert CT scans from 'Hounsfield' to 'Cormack' units to emphasize soft tissue contrast */
  h2c(): this;
  /** meshify requires 'd'ark, 'm'edium, 'b'right or numeric isosurface ('niimath bet -mesh -i d mesh.gii') */
  mesh(options?: MeshOptions): this;
  /** hollow out a mesh */
  hollow(threshold: string | number, thickness: string | number): this;
  /** modulus fractional remainder - same as '-rem' but includes fractions */
  mod(): this;
  /** binarize image using Otsu's method (mode 1..5; higher yields more bright voxels) */
  otsu(mode: string | number): this;
  /** raise the current image by following exponent */
  power(exponent: string | number): this;
  /** set qform_code */
  qform(code: string | number): this;
  /** set sform_code */
  sform(code: string | number): this;
  /** set maximum number of parallel threads. DISABLED: recompile for OpenMP support */
  p(threads: string | number): this;
  /** grow (>1) or shrink (<1) image. Method <m> (0=nearest,1=linear,2=spline,3=Lanczos,4=Mitchell) */
  resize(X: string | number, Y: string | number, Z: string | number, m: string | number): this;
  /** round voxels to the nearest integer */
  round(): this;
  /** linearly rescale intensities to the range 0–1 using global min/max */
  scale01(): this;
  /** estimate signed Euler Distance Transform (distance field). Assumes isotropic input */
  sedt(): this;
  /** fast edge detection */
  sobel(): this;
  /** sobel creating binary edge */
  sobel_binary(): this;
  /** convert FSL style upper triangle image to NIfTI standard lower triangle order */
  tensor_2lower(): this;
  /** convert NIfTI standard lower triangle image to FSL style upper triangle order */
  tensor_2upper(): this;
  /** as tensor_decomp except input stores lower diagonal (AFNI, ANTS, Camino convention) */
  tensor_decomp_lower(): this;
  /** truncates the decimal value from floating point value and returns integer value */
  trunc(): this;
  /** edge enhancing unsharp mask (sigma in mm, not voxels [1 is typical]; scl is amount [0.5 medium, 1.0 heavy]) */
  unsharp(sigma: string | number, scl: string | number): this;
  /** difference of gaussian with zero-crossing edges (positive and negative sigma mm) */
  dog(sPos: string | number, sNeg: string | number): this;
  /** as dog, without zero-crossing (raw rather than binarized data) */
  dogr(sPos: string | number, sNeg: string | number): this;
  /** as dog, zero-crossing for 2D sagittal slices */
  dogx(sPos: string | number, sNeg: string | number): this;
  /** as dog, zero-crossing for 2D coronal slices */
  dogy(sPos: string | number, sNeg: string | number): this;
  /** as dog, zero-crossing for 2D axial slices */
  dogz(sPos: string | number, sNeg: string | number): this;
  /** add following input to current image */
  add(input: string | number): this;
  /** subtract following input from current image */
  sub(input: string | number): this;
  /** multiply current image by following input */
  mul(input: string | number): this;
  /** divide current image by following input */
  div(input: string | number): this;
  /** modulus remainder - divide current image by following input and take remainder */
  rem(number: string | number): this;
  /** use (following image>0) to mask current image */
  mas(file: string | number): this;
  /** use following number to threshold current image (zero anything below the number) */
  thr(number: string | number): this;
  /** use following percentage (0-100) of ROBUST RANGE to threshold current image (zero anything below the number) */
  thrp(input: string | number): this;
  /** use following percentage (0-100) of ROBUST RANGE of non-zero voxels and threshold below */
  thrP(input: string | number): this;
  /** use following number to upper-threshold current image (zero anything above the number) */
  uthr(number: string | number): this;
  /** use following percentage (0-100) of ROBUST RANGE to upper-threshold current image (zero anything above the number) */
  uthrp(input: string | number): this;
  /** use following percentage (0-100) of ROBUST RANGE of non-zero voxels and threshold above */
  uthrP(input: string | number): this;
  /** use following percentage (0-100) of ROBUST RANGE to threshold current image (anything below set to this threshold) */
  clamp(input: string | number): this;
  /** use following percentage (0-100) of ROBUST RANGE to threshold current image (anything above set to this threshold) */
  uclamp(input: string | number): this;
  /** take maximum of following input and current image */
  max(input: string | number): this;
  /** take minimum of following input and current image */
  min(input: string | number): this;
  /** seed random number generator with following number */
  seed(number: string | number): this;
  /** replace the current image with input for future processing operations */
  restart(file: string | number): this;
  /** save the current working image to the input filename */
  save(): this;
  /** (-i i ip.c) intensity normalisation (per 3D volume mean) */
  inm(mean: string | number): this;
  /** (-I i ip.c) intensity normalisation, global 4D mean) */
  ing(mean: string | number): this;
  /** create a gauss kernel of sigma mm and perform mean filtering */
  s(sigma: string | number): this;
  /** exponential */
  exp(): this;
  /** natural logarithm */
  log(): this;
  /** sine function */
  sin(): this;
  /** cosine function */
  cos(): this;
  /** tangent function */
  tan(): this;
  /** arc sine function */
  asin(): this;
  /** arc cosine function */
  acos(): this;
  /** arc tangent function */
  atan(): this;
  /** square */
  sqr(): this;
  /** square root */
  sqrt(): this;
  /** reciprocal (1/current image) */
  recip(): this;
  /** absolute value */
  abs(): this;
  /** use (current image>0) to binarise */
  bin(): this;
  /** binarise and invert (binarisation and logical inversion) */
  binv(): this;
  /** fill holes in a binary mask (holes are internal - i.e. do not touch the edge of the FOV) */
  fillh(): this;
  /** fill holes using 26 connectivity */
  fillh26(): this;
  /** replace each nonzero voxel with a unique (subject to wrapping) index number */
  index(): this;
  /** add a 3D grid of intensity <value> with grid spacing <spacing> */
  grid(value: string | number, spacing: string | number): this;
  /** edge strength */
  edge(): this;
  /** enhance with TFCE, e.g. -tfce 2 0.5 6 (maybe change 6 to 26 for skeletons) */
  tfce(H: string | number, E: string | number, connectivity: string | number): this;
  /** show support area for voxel (X,Y,Z) */
  tfceS(H: string | number, E: string | number, connectivity: string | number, X: string | number, Y: string | number, Z: string | number, tfce_thresh: string | number): this;
  /** replace NaNs (improper numbers) with 0 */
  nan(): this;
  /** make NaN (improper number) mask with 1 for NaN voxels, 0 otherwise */
  nanm(): this;
  /** add uniform noise (range 0:1) */
  rand(): this;
  /** add Gaussian noise (mean=0 sigma=1) */
  randn(): this;
  /** set the output calmin/max to full data range */
  range(): this;
  /** convert a 4D (6-timepoint )tensor image into L1,2,3,FA,MD,MO,V1,2,3 (remaining image in pipeline is FA) */
  tensor_decomp(): this;
  /** 3x3x3 box centered on target voxel (set as default kernel) */
  kernel3D(): this;
  /** 3x3x1 box centered on target voxel */
  kernel2D(): this;
  /** all voxels in a cube of width <size> mm centered on target voxel */
  kernelBox(size: string | number): this;
  /** all voxels in a cube of width <size> voxels centered on target voxel, CAUTION: size should be an odd number */
  kernelBoxv(size: string | number): this;
  /** all voxels in a cuboid of dimensions X x Y x Z centered on target voxel, CAUTION: size should be an odd number */
  kernelBoxv3(X: string | number, Y: string | number, Z: string | number): this;
  /** gaussian kernel (sigma in mm, not voxels) */
  kernelGauss(sigma: string | number): this;
  /** all voxels in a sphere of radius <size> mm centered on target voxel */
  kernelSphere(size: string | number): this;
  /** use external file as kernel */
  kernelFile(filename: string | number): this;
  /** Mean Dilation of non-zero voxels */
  dilM(): this;
  /** Maximum Dilation of non-zero voxels (emulating output of fslmaths 6.0.1, max not modal) */
  dilD(): this;
  /** Maximum filtering of all voxels */
  dilF(): this;
  /** Apply -dilM repeatedly until the entire FOV is covered */
  dilall(): this;
  /** Erode by zeroing non-zero voxels when zero voxels found in kernel */
  ero(): this;
  /** Minimum filtering of all voxels */
  eroF(): this;
  /** Median Filtering */
  fmedian(): this;
  /** Mean filtering, kernel weighted (conventionally used with gauss kernel) */
  fmean(): this;
  /** Mean filtering, kernel weighted, un-normalized (gives edge effects) */
  fmeanu(): this;
  /** downsamples image by a factor of 2 (keeping new voxels centered on old) */
  subsamp2(): this;
  /** downsamples image by a factor of 2 (non-centered) */
  subsamp2offc(): this;
  /** mean across time */
  Tmean(): this;
  /** standard deviation across time */
  Tstd(): this;
  /** sum across time */
  Tsum(): this;
  /** max across time */
  Tmax(): this;
  /** time index of max across time */
  Tmaxn(): this;
  /** min across time */
  Tmin(): this;
  /** median across time */
  Tmedian(): this;
  /** nth percentile (0-100) of FULL RANGE across time */
  Tperc(percentage: string | number): this;
  /** temporal AR(1) coefficient (use -odt float and probably demean first) */
  Tar1(): this;
  /** Nonparametric uncorrected P-value, assuming timepoints are the permutations; first timepoint is actual (unpermuted) stats image */
  pval(): this;
  /** Same as -pval, but treat zeros as missing data */
  pval0(): this;
  /** Same as -pval, but gives FWE corrected P-values */
  cpval(): this;
  /** Convert Z-stat to (uncorrected) P */
  ztop(): this;
  /** Convert (uncorrected) P to Z */
  ptoz(): this;
  /** Convert Z-stat to (uncorrected but clamped) P */
  ztopc(): this;
  /** Convert (uncorrected but clamped) P to Z */
  ptozc(): this;
  /** Convert data to ranks (over T dim) */
  rank(): this;
  /** Transform to Normal dist via ranks */
  ranknorm(): this;
  /** zero outside roi (using voxel coordinates). Inputting -1 for a size will set it to the full image extent for that dimension */
  roi(xmin: string | number, xsize: string | number, ymin: string | number, ysize: string | number, zmin: string | number, zsize: string | number, tmin: string | number, tsize: string | number): this;
  /** (-t in ip.c) Bandpass temporal filtering; nonlinear highpass and Gaussian linear lowpass (with sigmas in volumes, not seconds); set either sigma<0 to skip that filter */
  bptf(hp_sigma: string | number, lp_sigma: string | number): this;
  /** take (normally binary) truth and test current image in ROC analysis against truth. <AROC-thresh> is usually 0.05 and is limit of Area-under-ROC measure FP axis. <outfile> is a text file of the ROC curve (triplets of values: FP TP threshold). If the truth image contains negative voxels these get excluded from all calculations. If <AROC-thresh> is positive then the [4Dnoiseonly] option needs to be set, and the FP rate is determined from this noise-only data, and is set to be the fraction of timepoints where any FP (anywhere) is seen, as found in the noise-only 4d-dataset. This is then controlling the FWE rate. If <AROC-thresh> is negative the FP rate is calculated from the zero-value parts of the <truth> image, this time averaging voxelwise FP rate over all timepoints. In both cases the TP rate is the average fraction of truth=positive voxels correctly found */
  roc(AROC_thresh: string | number, outfile: string | number, truth: string | number): this;
}

// Output data types
export type DataType = "char" | "short" | "int" | "float" | "double" | "input";

export const dataTypes = {
  char: "char" as const,
  short: "short" as const,
  int: "int" as const,
  float: "float" as const,
  double: "double" as const,
  input: "input" as const,
} as const;
