import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Define types for the operators JSON structure
interface SubOperation {
  args: string[];
  help: string;
}

interface OperatorDefinition {
  args?: string[];
  help?: string;
  subOperations?: Record<string, SubOperation>;
}

type Operators = Record<string, OperatorDefinition>;

// Read the operators JSON file
const operatorsPath = path.join(__dirname, '../src/niimathOperators.json');
const operators = JSON.parse(fs.readFileSync(operatorsPath, 'utf8')) as Operators;

// Helper to convert argument names to camelCase type names
function toCamelCase(str: string): string {
  return str.replace(/([-_][a-z])/g, (group) => group.toUpperCase().replace('-', '').replace('_', ''));
}

// Helper to create valid TypeScript parameter names
function toParamName(arg: string): string {
  // Remove angle brackets and convert to valid identifier
  return arg.replace(/[<>]/g, '').replace(/[^a-zA-Z0-9_]/g, '_');
}

function generateTypes(): string {
  let output = '// Auto-generated TypeScript definitions from niimathOperators.json\n';
  output += '// Do not edit this file directly - it will be overwritten\n\n';

  // Generate operator definitions interface
  output += 'export interface OperatorDefinition {\n';
  output += '  args?: string[];\n';
  output += '  help?: string;\n';
  output += '  subOperations?: Record<string, { args: string[]; help: string }>;\n';
  output += '}\n\n';

  output += 'export type Operators = Record<string, OperatorDefinition>;\n\n';

  // Generate specific types for mesh options
  if (operators.mesh && operators.mesh.subOperations) {
    output += '// Mesh sub-operation options\n';
    output += 'export interface MeshOptions {\n';
    Object.entries(operators.mesh.subOperations).forEach(([key, def]) => {
      const comment = `  /** ${def.help} */\n`;
      output += comment;
      if (def.args.length === 0) {
        output += `  ${key}?: boolean;\n`;
      } else if (def.args.length === 1) {
        output += `  ${key}?: string | number;\n`;
      } else {
        output += `  ${key}?: (string | number)[];\n`;
      }
    });
    output += '}\n\n';
  }

  // Generate specific types for bitmap options
  if (operators.bitmap && operators.bitmap.subOperations) {
    output += '// Bitmap sub-operation options\n';
    output += 'export interface BitmapOptions {\n';
    Object.entries(operators.bitmap.subOperations).forEach(([key, def]) => {
      const comment = `  /** ${def.help} */\n`;
      output += comment;
      if (def.args.length === 0) {
        output += `  ${key}?: boolean;\n`;
      } else if (def.args.length === 1) {
        output += `  ${key}?: string | number;\n`;
      } else {
        output += `  ${key}?: (string | number)[];\n`;
      }
    });
    output += '}\n\n';
  }

  // Generate ImageProcessor interface with all methods
  output += '// ImageProcessor method signatures\n';
  output += 'export interface ImageProcessorMethods {\n';

  Object.entries(operators).forEach(([methodName, definition]) => {
    if (methodName === 'kernel' && definition.subOperations) {
      // Generate kernel methods
      Object.entries(definition.subOperations).forEach(([subOpName, subOpDef]) => {
        const kernelMethodName = `kernel${subOpName.charAt(0).toUpperCase() + subOpName.slice(1)}`;
        const comment = `  /** ${subOpDef.help} */\n`;
        output += comment;

        if (subOpDef.args.length === 0) {
          output += `  ${kernelMethodName}(): this;\n`;
        } else {
          const params = subOpDef.args.map(arg => `${toParamName(arg)}: string | number`).join(', ');
          output += `  ${kernelMethodName}(${params}): this;\n`;
        }
      });
    } else if (methodName === 'mesh') {
      const comment = `  /** ${definition.help} */\n`;
      output += comment;
      output += `  mesh(options?: MeshOptions): this;\n`;
    } else if (methodName === 'bitmap') {
      const comment = `  /** ${definition.help} */\n`;
      output += comment;
      output += `  bitmap(outputPath: string, options?: BitmapOptions): this;\n`;
    } else {
      // Regular methods
      const comment = `  /** ${definition.help} */\n`;
      output += comment;

      if (definition.args && definition.args.length === 0) {
        output += `  ${methodName}(): this;\n`;
      } else if (definition.args && definition.args.length > 0) {
        const params = definition.args.map(arg => `${toParamName(arg)}: string | number`).join(', ');
        output += `  ${methodName}(${params}): this;\n`;
      }
    }
  });

  output += '}\n\n';

  // Generate data types
  output += '// Output data types\n';
  output += 'export type DataType = "char" | "short" | "int" | "float" | "double" | "input";\n\n';

  output += 'export const dataTypes = {\n';
  output += '  char: "char" as const,\n';
  output += '  short: "short" as const,\n';
  output += '  int: "int" as const,\n';
  output += '  float: "float" as const,\n';
  output += '  double: "double" as const,\n';
  output += '  input: "input" as const,\n';
  output += '} as const;\n';

  return output;
}

// Generate and write the types file
const typesContent = generateTypes();
const outputPath = path.join(__dirname, '../src/types.ts');
fs.writeFileSync(outputPath, typesContent);
console.log('TypeScript definitions generated at:', outputPath);
