#!/usr/bin/env python3
"""Generate src/mindgrab_weights.c from the upstream MindGrab model.pth.

  python3 scripts/export_mindgrab.py [--pth ~/.cache/brainchop/models/mindgrab/model.pth]

Requires torch and numpy; it is a developer tool, not part of any build. The generated
file is committed, so a normal `BRAINCHOP=1` build needs neither Python nor the .pth.

Two runs on the same input are byte-identical.

Layout notes that the C kernel depends on -- change these and mindgrab.c breaks silently:

* Spatial axes are REVERSED. brainchop feeds the network `volume.transpose((2,1,0))`,
  i.e. the tensor's (D,H,W) axes are the NIfTI (x,y,z) axes, while niimath holds voxels
  x-fastest. A tap at torch kernel index (kd,kh,kw) is therefore the (dx,dy,dz) offset
  (kd-1,kh-1,kw-1)*dilation, so in x-fastest order the kernel is transposed.
* Per-layer weights are emitted as [tap][in_channel][out_channel] with
  tap = tz*9 + ty*3 + tx (tx fastest), so the C inner loop over out-channels is
  contiguous and vectorises.
* The final 1x1x1 classifier is [in_channel][out_channel], followed by its 2 biases.
"""
import argparse
import hashlib
import os
import sys

import numpy as np

# The artifact this exporter was validated against.
PTH_URL = "https://huggingface.co/neuroneural/mindgrab/resolve/main/model.pth"
PTH_SHA256 = "31f1bda17b8d3eee17a54cf3f199899763a6615a049f05ab2a05f18eb98ec23a"

CHANNELS = 15
NCLASS = 2
NHIDDEN = 25  # conv+groupnorm+gelu blocks
DILATIONS = [16, 8, 4, 2, 1] * 5


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def load(pth):
    import torch

    sd = torch.load(pth, map_location="cpu", weights_only=True)
    keys = ["model.%d.0.weight" % i for i in range(NHIDDEN)] + [
        "model.%d.weight" % NHIDDEN, "model.%d.bias" % NHIDDEN]
    if list(sd.keys()) != keys:
        raise SystemExit("unexpected state_dict keys: %s" % list(sd.keys()))
    out = []
    for i in range(NHIDDEN):
        w = sd[keys[i]].numpy().astype(np.float32)
        want = (CHANNELS, 1 if i == 0 else CHANNELS, 3, 3, 3)
        if w.shape != want:
            raise SystemExit("layer %d shape %s, expected %s" % (i, w.shape, want))
        # (oc,ic,kd,kh,kw) -> (kw,kh,kd,ic,oc) == (tz,ty,tx,ic,oc)
        out.append(np.ascontiguousarray(w.transpose(4, 3, 2, 1, 0)).ravel())
    w = sd[keys[NHIDDEN]].numpy().astype(np.float32)
    if w.shape != (NCLASS, CHANNELS, 1, 1, 1):
        raise SystemExit("classifier shape %s" % (w.shape,))
    out.append(np.ascontiguousarray(w.reshape(NCLASS, CHANNELS).T).ravel())
    b = sd[keys[NHIDDEN + 1]].numpy().astype(np.float32)
    if b.shape != (NCLASS,):
        raise SystemExit("bias shape %s" % (b.shape,))
    out.append(b.ravel())
    return np.concatenate(out)


def fmt(v):
    # 9 significant digits round-trips float32 exactly (FLT_DECIMAL_DIG)
    s = "%.9g" % v
    return s + "f" if ("." in s or "e" in s or "n" in s) else s + ".f"


def emit(vals, digest, dst):
    n = len(vals)
    lines = []
    lines.append("// Generated by scripts/export_mindgrab.py -- DO NOT EDIT.\n")
    lines.append("// MindGrab weights, %d float32 parameters (%d bytes of .rodata).\n"
                 % (n, 4 * n))
    lines.append("// Source: %s\n" % PTH_URL)
    lines.append("// SHA-256: %s\n" % digest)
    lines.append("// MIT licensed; see src/mindgrab.LICENSE for provenance and citation.\n")
    lines.append('#include "mindgrab_weights.h"\n\n')
    lines.append("const float mindgrab_weights[MINDGRAB_NPARAM] = {\n")
    row = []
    for i, v in enumerate(vals):
        row.append(fmt(v))
        if len(row) == 8:
            lines.append("\t" + ",".join(row) + ",\n")
            row = []
    if row:
        lines.append("\t" + ",".join(row) + ",\n")
    lines.append("};\n")
    body = "".join(lines)
    with open(dst, "w", newline="\n") as f:
        f.write(body)
    return n


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pth", default=os.path.expanduser(
        "~/.cache/brainchop/models/mindgrab/model.pth"))
    ap.add_argument("--out", default=os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "src", "mindgrab_weights.c"))
    ap.add_argument("--allow-hash-mismatch", action="store_true")
    a = ap.parse_args()

    digest = sha256(a.pth)
    if digest != PTH_SHA256 and not a.allow_hash_mismatch:
        raise SystemExit("SHA-256 mismatch\n  got      %s\n  expected %s" % (digest, PTH_SHA256))
    vals = load(a.pth)
    expect = 405 + 24 * CHANNELS * CHANNELS * 27 + NCLASS * CHANNELS + NCLASS
    if len(vals) != expect:
        raise SystemExit("got %d parameters, expected %d" % (len(vals), expect))
    n = emit(vals, digest, a.out)
    print("wrote %s (%d parameters)" % (a.out, n))


if __name__ == "__main__":
    sys.exit(main())
