#ifndef MINDGRAB_WEIGHTS_H
#define MINDGRAB_WEIGHTS_H

// MindGrab network shape. mindgrab_weights.c is generated by scripts/export_mindgrab.py
// and its layout is described there; mindgrab.c is the only consumer.

#define MINDGRAB_DIM 256                        // conformed grid, 256^3
#define MINDGRAB_CHAN 15                        // hidden channels
#define MINDGRAB_NCLASS 2                       // background / brain
#define MINDGRAB_NHIDDEN 25                     // conv + GroupNorm + GELU blocks
#define MINDGRAB_NPARAM 146237                  // total float32 parameters

// Offsets into mindgrab_weights[]: hidden layer i starts at MINDGRAB_LOFF(i).
#define MINDGRAB_L0_N (MINDGRAB_CHAN * 1 * 27)  // 405
#define MINDGRAB_LN_N (MINDGRAB_CHAN * MINDGRAB_CHAN * 27) // 6075
#define MINDGRAB_LOFF(i) ((i) == 0 ? 0 : MINDGRAB_L0_N + ((i) - 1) * MINDGRAB_LN_N)
#define MINDGRAB_CLS_OFF (MINDGRAB_L0_N + 24 * MINDGRAB_LN_N) // 1x1x1 classifier
#define MINDGRAB_BIAS_OFF (MINDGRAB_CLS_OFF + MINDGRAB_NCLASS * MINDGRAB_CHAN)

#ifdef __cplusplus
extern "C" {
#endif

extern const float mindgrab_weights[MINDGRAB_NPARAM];

#ifdef __cplusplus
}
#endif

#endif // MINDGRAB_WEIGHTS_H
