name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  pypi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false  # niimath has no submodules

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - uses: casperdcl/deploy-pypi@v2
        with:
          build: -s
          upload: true
        env:
          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ""  # Disable OIDC flow
          ACTIONS_ID_TOKEN_REQUEST_URL: ""    # Disable OIDC flow
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
