name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  pypi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false  # niimath has no submodules

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Environment variables set as secrets
      - name: Set up PyPI credentials
        run: |
          echo "Setting up PyPI credentials"
          echo ${{ secrets.PYPI_API_TOKEN }} | sed 's/./*/g'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

      - uses: casperdcl/deploy-pypi@v2
        with:
          build: -s
          upload: true
          registry_domain: "https://upload.pypi.org"
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
