name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  pypi:
    permissions:
      id-token: write  # Required for trusted publishing to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python build tools
        run: |
          pip install build twine

      - name: Configure and build niimath binary
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Copy binary into Python package
        run: |
          cp build/niimath niimath/niimath
          chmod +x niimath/niimath

      - name: Build Python package (wheel and sdist)
        run: |
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
